version: '3'
services:
  backend:
    build: ./app/backend
    ports: #expose our IP
      - "5000:5000"
  frontend:
    build: 
      conext: ./app/frontend
      dockerfile: frontend
    ports: #expose our IP
      - "3000:3000"
    depends_on:
      - backend