version: '3'
services:
  backend:
    build: ./app/backend
    volumes:
      - '.:/app'
    stdin_open: true
  frontend:
    build: ./app/frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports: #expose our IP
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true